# Generated by Django 2.1.7 on 2019-02-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190226_1234'),
        ('main', '0005_auto_20190226_1317'),
    ]

    operations = [
    ]
