# Generated by Django 2.1.7 on 2019-03-12 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190227_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
