# Generated by Django 2.1.7 on 2019-03-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_reg_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='reg_date',
            new_name='registration_starts',
        ),
    ]
