# Generated by Django 2.1.7 on 2019-03-12 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190312_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_starts',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
