# Generated by Django 2.1.5 on 2019-03-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event_capacity'),
        ('main', '0012_auto_20190312_1204'),
    ]

    operations = [
    ]
